// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// archmCopulaLink_cpp
NumericVector archmCopulaLink_cpp(std::string fam, double param, NumericVector p);
RcppExport SEXP _CopulaSCR_archmCopulaLink_cpp(SEXP famSEXP, SEXP paramSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fam(famSEXP);
    Rcpp::traits::input_parameter< double >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(archmCopulaLink_cpp(fam, param, p));
    return rcpp_result_gen;
END_RCPP
}
// archmCopulaLink_dev_cpp
NumericVector archmCopulaLink_dev_cpp(std::string fam, double param, NumericVector js);
RcppExport SEXP _CopulaSCR_archmCopulaLink_dev_cpp(SEXP famSEXP, SEXP paramSEXP, SEXP jsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fam(famSEXP);
    Rcpp::traits::input_parameter< double >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type js(jsSEXP);
    rcpp_result_gen = Rcpp::wrap(archmCopulaLink_dev_cpp(fam, param, js));
    return rcpp_result_gen;
END_RCPP
}
// archmCopulaLink_inv_cpp
NumericVector archmCopulaLink_inv_cpp(std::string fam, double param, NumericVector y);
RcppExport SEXP _CopulaSCR_archmCopulaLink_inv_cpp(SEXP famSEXP, SEXP paramSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fam(famSEXP);
    Rcpp::traits::input_parameter< double >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(archmCopulaLink_inv_cpp(fam, param, y));
    return rcpp_result_gen;
END_RCPP
}
// dev_Copula_cpp
NumericVector dev_Copula_cpp(std::string fam, double param, NumericVector p1, NumericVector p2, std::string mode);
RcppExport SEXP _CopulaSCR_dev_Copula_cpp(SEXP famSEXP, SEXP paramSEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fam(famSEXP);
    Rcpp::traits::input_parameter< double >::type param(paramSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    rcpp_result_gen = Rcpp::wrap(dev_Copula_cpp(fam, param, p1, p2, mode));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CopulaSCR_archmCopulaLink_cpp", (DL_FUNC) &_CopulaSCR_archmCopulaLink_cpp, 3},
    {"_CopulaSCR_archmCopulaLink_dev_cpp", (DL_FUNC) &_CopulaSCR_archmCopulaLink_dev_cpp, 3},
    {"_CopulaSCR_archmCopulaLink_inv_cpp", (DL_FUNC) &_CopulaSCR_archmCopulaLink_inv_cpp, 3},
    {"_CopulaSCR_dev_Copula_cpp", (DL_FUNC) &_CopulaSCR_dev_Copula_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_CopulaSCR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
