# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

archmCopulaLink_cpp <- function(fam, param, p) {
    .Call(`_CopulaSCR_archmCopulaLink_cpp`, fam, param, p)
}

archmCopulaLink_dev_cpp <- function(fam, param, js) {
    .Call(`_CopulaSCR_archmCopulaLink_dev_cpp`, fam, param, js)
}

archmCopulaLink_inv_cpp <- function(fam, param, y) {
    .Call(`_CopulaSCR_archmCopulaLink_inv_cpp`, fam, param, y)
}

dev_Copula_cpp <- function(fam, param, p1, p2, mode = "1") {
    .Call(`_CopulaSCR_dev_Copula_cpp`, fam, param, p1, p2, mode)
}

